### ISSUE TITLE
java.lang.ClassCastException:

### ISSUE THREAD

**Issue by cellojaan** [syedowaisali/crystal-range-seekbar#137]
I got error when I set the RangeSeekbar.

**Error code:**
`java.lang.ClassCastException: com.crystal.crystalrangeseekbar.widgets.CrystalSeekbar cannot be cast to com.crystal.crystalrangeseekbar.widgets.CrystalRangeSeekbar
        at com.vevogram.app.FragmentSearch.onCreateView(FragmentSearch.java:57)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

**Setup code:**
`CrystalRangeSeekbar rangeSeekbar1 = view.findViewById(R.id.range1);
        CrystalRangeSeekbar rangeSeekbar2 = view.findViewById(R.id.range2);
        final TextView rangeText1 = view.findViewById(R.id.rangeText1);
        final TextView rangeText2 = view.findViewById(R.id.rangeText2);

        rangeSeekbar1.setOnRangeSeekbarChangeListener(new OnRangeSeekbarChangeListener() {
            @Override
            public void valueChanged(Number minValue, Number maxValue) {
                rangeText1.setText(String.valueOf(maxValue));
            }
        });

        // set final value listener
        rangeSeekbar1.setOnRangeSeekbarFinalValueListener(new OnRangeSeekbarFinalValueListener() {
            @Override
            public void finalValue(Number minValue, Number maxValue) {
                rangeText1.setText(String.valueOf(maxValue));
            }
        });

        rangeSeekbar2.setOnRangeSeekbarChangeListener(new OnRangeSeekbarChangeListener() {
            @Override
            public void valueChanged(Number minValue, Number maxValue) {
                rangeText2.setText(String.valueOf(maxValue));
            }
        });

        // set final value listener
        rangeSeekbar2.setOnRangeSeekbarFinalValueListener(new OnRangeSeekbarFinalValueListener() {
            @Override
            public void finalValue(Number minValue, Number maxValue) {
                rangeText2.setText(String.valueOf(maxValue));
            }
        });`

The API Level is 28. Any body have a idea?

**Comment by appukrb** [comment]
hi,
post your xml file that will be helpful to close your issue
