### ISSUE TITLE
I try to set shape drawable - and ap crashed!

### ISSUE THREAD

**Issue by roninua** [syedowaisali/crystal-range-seekbar#14]
app:left_thumb_image="@drawable/tmp"

_/drawable/tmp.xml_

`    <shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="oval">
    <solid android:color="#bada55"/>
    <size android:width="20dp" android:height="20dp"/>
    </shape>`

How i can set shape drawable and vector drawable to the thumb?

**Comment by TheLester** [comment]
`         Caused by: java.lang.ClassCastException: android.graphics.drawable.GradientDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
                                                       at com.crystal.crystalrangeseekbar.widgets.CrystalRangeSeekbar.getBitmap(CrystalRangeSeekbar.java:481)
                                                       at com.crystal.crystalrangeseekbar.widgets.CrystalRangeSeekbar.init(CrystalRangeSeekbar.java:169)
                                                       at com.crystal.crystalrangeseekbar.widgets.CrystalRangeSeekbar.<init>(CrystalRangeSeekbar.java:157)
                                                       at com.crystal.crystalrangeseekbar.widgets.CrystalRangeSeekbar.<init>(CrystalRangeSeekbar.java:122)`

**Comment by MohammadBarati** [comment]
it seems this version don't support xml Files like Shape or Svg
I hope this feature work in the future

**Comment by donedeal-ronan** [comment]
Is there any update on this bug?

**Comment by syedowaisali** [comment]
not supported yet, available soon
